### ISSUE TITLE
关于测试的准确率

### ISSUE THREAD

**Issue by Wang-pengfei** [thuml/OpenDG-DAML#1]
你好，我第一次接触这个领域，试着跑了一下代码。在Office-Home数据集上，测试得到这个结果：
Target Domain:  R
Best OverallAcc: 61.54 Best threshold Acc: 0.584 Best OverallHscore: 61.16 Best threshold Hscore: 0.481 Best OverallCaa: 61.18 Best threshold Caa: 0.584

我想问一下，论文中所列出的结果是和哪几个结果对应的？

**Comment by sy565612345** [comment]
您好，这里您跑的测试是对整个target domain中的数据进行的（包括了其中的known classes和open classes），这部分测试结果中的 Best OverallHscore: 61.16，对应我们论文中的H-score。

我们论文中还汇报了只测target domain中known classses的结果即文中的Acc，这一结果在训练过程中已输出。

**Comment by Wang-pengfei** [comment]
Thanks！

**Comment by cht619** [comment]
您好，我用Office_home_Resnet50特征进行实验：
1. Best threshold Acc: 0.897, Best threshold Hscore: 0.897. 都是90%左右，这正常吗？
2. 可以直接使用resnet-50特征作为输入不？会被认可吗
