### ISSUE TITLE
Clarifications on results by running the code

### ISSUE THREAD

**Issue by nkv1995** [thuml/OpenDG-DAML#3]
I modified the run_train.sh script  to train of PAC-S setting as below: 
`cd ..`
`gpu=0`
`ipe=70 #(1670 images in Photo divided by batch size 24)`
`source=PAC`
`target=S`
`log_name=daml-${source}-${target}`
`python daml.py     --root ./Datasets/PACS     -d PACS     -s ${source}     -t ${target}     --gpu ${gpu}     --iters_per_epoch {ipe}  --savename ${log_name}`

Final Results at the end of training for default 30 epochs:
`best_val_acc1 = 95.7, 45.3`
`best_test_acc1 = 49.7`

This `best_test_acc1` do not match the results in Table 2 (Acc. column under Sketch Domain). I didn't not change anything in daml.py script. Please let me know if I missed something. 

Moreover, by running run_validate.sh, I get 

`Best OverallAcc: 46.25 Best threshold Acc: 0.223 Best OverallHscore: 42.50 Best threshold Hscore: 0.562 Best OverallCaa: 39.89 Best threshold Caa: 0.223`

`Environment:
	Python: 3.6.9
	PyTorch: 1.7.1+cu101
	Torchvision: 0.8.2+cu101
	CUDA: 10.1
	CUDNN: 7603
	NumPy: 1.19.5
	PIL: 8.3.2`

**Comment by sy565612345** [comment]
Hello, maybe you can train fewer iterations, such as setting ipe=31, to avoid over-fitting.
