### ISSUE TITLE
Question about how to implement DAML-S

### ISSUE THREAD

**Issue by Noguchi-Masashi** [thuml/OpenDG-DAML#5]
Hi,
Thanks for your excellent work and code!

In Appendix, You evaluate DAML-S where the three domains each have a specific classifier but share the whole backbone.
I would like to know how to implement DAML-S.

Would the following changes make DAML a DAML-S?

```python
backbone1 = resnet18_fast()
#backbone2 = resnet18_fast()
#backbone3 = resnet18_fast()

classifier = ClassifierFast(backbone1, backbone1, backbone1, num_classes).cuda()
```

Thank you in advance.

**Comment by jis3613** [comment]
You have to alter the daml_utils.py file.
You have to define a new class that only uses one backbone and multi heads.

**Comment by Noguchi-Masashi** [comment]
Thank you for your kind response.
